---
title: "viz"
author: "Ben Best"
date: "April 16, 2016"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Load

- load libraries
- inspect

```{r load, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2) # install.packages('ggplot2')
library(gapminder)

# preview data
gapminder

# get range of available data
summary(gapminder)

# setup dataframe
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions
```

## Simple Scatterplot

```{r}
# plot scatterplot of most recent year 
s = ggplot(g, aes(x=gdpPercap, y=lifeExp)) +
  geom_point()
s
```

## With Aesthetics and Labels

```{r}
# add aesthetic of size by population, color by continent
s = ggplot(g, aes(x=gdpPercap, y=lifeExp, 
                  size=pop_m, colour=continent, key=country)) +
  geom_point() +
  # add title, update axes labels
  ggtitle('Health & Wealth of Nations for 2007') +
  xlab('GDP per capita ($/year)') +
  ylab('Life expectancy (years)') +
  # label legend
  scale_colour_discrete(name='Continent') +
  scale_size_continuous(name='Population (M)')
s
```

## Interactive

```{r, message=FALSE, warning=FALSE, eval=FALSE}
library(plotly) # install.packages('plotly')
ggplotly(s)
```

## Boxplot

```{r}
b = ggplot(g, aes(x=continent, y=lifeExp)) +
  geom_boxplot()
b
```

## Data Table

```{r}
library(DT) # install.packages('DT')
datatable(gapminder)
```

## Map

```{r}
library(tmap) # install.packages('tmap')

# load world spatial polygons
data(World)

# inspect values in World
World@data %>% tbl_df()

# gapminder countries not in World. skipping for now
g %>% 
  anti_join(World@data, by=c('country'='name')) %>% 
  arrange(desc(pop))

# World countries not in gapminder. skipping for now
World@data %>% 
  anti_join(g, by=c('name'='country')) %>% 
  arrange(desc(pop_est)) %>%
  select(iso_a3, name, pop_est)

# join gapminder data to World
World@data = World@data %>%
  left_join(g, by=c('name'='country'))
```

```{r}
# make map
m = tm_shape(World) +
    tm_polygons('lifeExp', palette='RdYlGn', id='name', title='Life expectancy (years)', auto.palette.mapping=F) +
    tm_style_gray() + tm_format_World()
m
```

```{r}
# show interactive map
tmap_leaflet(m)
```

